// =============================================================
// 
// 	reducer_books.js
//
// =============================================================
 
// more on reducers here : http://redux.js.org/docs/basics/Reducers.html
// in short, a reducer is a function that returns a piece of the application's state / model / data
// reducers produce the VALUE of our state
// good to keep in mind that each piece of the app should be named after the folder its in, to be concise

// create the JS to hold the book data
function restaurantReducer() {
	
	// returns an array with our data
	return [

		{ image: '', category: 'oriental', title: 'pho dac biet', rating: 3, description: 'Order your favorite Vietnamese cousine, delivery available', price:'15', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'oriental', title: 'golden dragon', rating: 4, description: 'Order your favorite Chinese cousine, Pick up only', price:'20', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'fast food', title: 'fat burger', rating: 2, description: 'Call to order for delivery or pickup, best burgers in town', price:'10', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'fast food', title: 'shake & fries', rating: 3, description: 'Best Shakes & Fries in the city, call today to order', price:'10', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'mexican', title: 'tacotime', rating: 2, description: 'Delicious mexican food, visit us today to satisfy your craving', price:'10', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'mexican', title: 'los chilitos taqueria', rating: 5, description: 'Winner of the 2016 most delicious Burrito competition', price:'15', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'indian', title: 'taj mahal', rating: 4, description: 'Kick-off your Indian meal by picking from a wide selection of', price:'25', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'indian', title: 'khana khazana', rating: 3, description: 'View our Indian Cousine, our family deal is on special', price:'25', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' },
		{ image: '', category: 'greek', title: 'broken plate', rating: 5, description: 'Taste Greece with our world-reknown greek dishes', price:'30', ldescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus mi arcu, in lobortis risus vehicula quis. Proin pellentesque turpis eget lectus tincidunt, ut ornare velit imperdiet. Duis finibus nunc eget ante cursus, sit amet feugiat augue viverra. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis congue risus sem, varius mattis mi dictum sed. Nullam vitae iaculis odio, ac finibus odio. In laoreet a tellus quis gravida. Aliquam venenatis, velit aliquet euismod convallis, nisl sem ultrices mauris, sit amet gravida dui nunc a lectus.' }
	
	];
};

export default restaurantReducer;